services:

  # NextJS webserver
  nextjs:
    build:
      context: .
    ports:
      - 5000:5000
    networks:
      - internal

  # NGinx reverse proxy
  nginx:
    image: nginx:alpine

    depends_on:
      - nextjs

    ports:
      - 443:443
    networks:
      - internal
      - external

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # - ./nginx/favicons/:/favicons/:ro

      - /etc/letsencrypt/live/skoh.tv/fullchain.pem:/etc/ssl/skoh-tv/fullchain.pem:ro
      - /etc/letsencrypt/live/skoh.tv/privkey.pem:/etc/ssl/skoh-tv/privkey.pem:ro


networks:
  internal:
    name: internal
    internal: true
  external:
    name: external
